config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from .views import (index_view, )

urlpatterns = [
                    path(r'', index_view, name='site_index'),
                    path(r'admin/', admin.site.urls, name='admin'),
                  # markdownx
                  path(r'markdownx/', include('markdownx.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

isppme/users/urls.py
from django.urls import path

from isppme.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

isppme/accounts/models.py
import requests
from six.moves.urllib_parse import quote_plus, parse_qs

from django.db import models
from django.utils.translation import ugettext_lazy as _

from paynow import StatusResponse

from isppme.core.models import UUIDModel


class DebitLedger(UUIDModel):
    """Stores ledger entries made to a student's record. These might include
    Tuition, Registration Fees, Exam Fees etc.
    This model only stores debited items. Credits/Payments have their own model.
    """

    registration = models.ForeignKey(
        to="enrollments.Registration", on_delete=models.CASCADE, related_name="debit_ledger_entries",
        verbose_name=_("Student"), help_text=_("Reference to student registration record"),
    )

    narration = models.CharField(
        verbose_name=_("Narration"), max_length=255,
        help_text=_("Entry label or narration e.g. Semester 1 Tuition.")
    )

    amount = models.DecimalField(
        verbose_name=_("Amount"), max_digits=19, decimal_places=2,
        help_text=_("Amount debited")
    )
    merchant_code = models.CharField(
        verbose_name='Paynow merchant code', max_length=255,
    )

    required = models.BooleanField(
        verbose_name=_("Required"), default=True, editable=False,
        help_text=_("Indicates if this fee entry is required for the student to access portal privileges.")
    )

    class Meta:
        verbose_name = _("Debit ledger entry")
        verbose_name_plural = _("Debit ledger entries")
        ordering = ("created",)

    def __str__(self):
        return f"{str(self.narration)} - ${str(self.amount)}"

    @property
    def merchant(self):
        from isppme.accounts.models import PaynowMerchant
        qs = PaynowMerchant.objects.filter(
            code=self.merchant_code
        )
        if qs.exists():
            return qs[0]
        return None
    

    @property
    def paid(self):
        credit_entries = self.credit_entries.all()
        if credit_entries.count() > 0:
            paid_total = 0
            for entry in credit_entries:
                paid_total += entry.amount
            if paid_total < self.amount:
                return False
            return True
        return False


class CreditLedger(UUIDModel):
    """Stores ledger entries made to a student's record. These might include
    Tuition, Registration Fees, Exam Fees etc.
    This model only stores credit items. Debits/Deductions have their own model.
    """
    registration = models.ForeignKey(
        to="enrollments.Registration", on_delete=models.CASCADE, related_name="credit_ledger_entries",
        verbose_name=_("Student"), help_text=_("Reference to student registration record"),
    )

    debit_ref = models.ForeignKey(
        to='accounts.DebitLedger', on_delete=models.SET_NULL, related_name="credit_entries",
        verbose_name=_("Debit reference"), help_text=_("Reference to debit entry"), null=True, blank=True,
    )

    narration = models.CharField(
        verbose_name=_("Narration"), max_length=255,
        help_text=_("Entry label or narration e.g. Semester 1 Tuition.")
    )

    amount = models.DecimalField(
        verbose_name=_("Amount"), max_digits=19, decimal_places=2,
        help_text=_("Amount debited")
    )
    transaction = models.ForeignKey(
        to="accounts.Transaction", on_delete=models.SET_NULL, related_name="payments",
        null=True, blank=True, verbose_name=_("Transactions"),
    )
    payment_ref = models.CharField(
        verbose_name=_("Payment reference"), max_length=255,
        help_text=_("Stores payment reference i.e. Proof of payment or check no."),
    )

    class Meta:
        verbose_name = _("Credit ledger entry")
        verbose_name_plural = _("Credit ledger entries")
        ordering = ("transaction", "-created",)

    def __str__(self):
        return f"{str(self.narration)} - ${str(self.amount)}"


class PaynowMerchant(UUIDModel):
    code = models.CharField(
        verbose_name=_('Code'), unique=True, max_length=255,
    )
    name = models.CharField(
        verbose_name=_("Name"), max_length=255,
        help_text=_("Credentials name or destination account name to identify with.")
    )
    integration_id = models.PositiveIntegerField(
        verbose_name=_("Integration ID"),
        help_text=_("Paynow integration ID as provided by Paynow.")
    )
    integration_key = models.CharField(
        verbose_name=_("Integration Key"), max_length=255,
        help_text=_("Paynow integration key as provided by Paynow.")
    )

    class Meta:
        verbose_name = _("ISPPME Paynow merchant")
        verbose_name_plural = _("ISPPME Paynow merchants")

    def __str__(self):
        return f"{str(self.name)}"


class Transaction(UUIDModel):
    """Stores paynow variables
    """

    debit_ref = models.ForeignKey(
        to='accounts.DebitLedger', verbose_name=_("Debit ref."), on_delete=models.SET_NULL,
        related_name="transactions", null=True, blank=True,
    )
    link = models.CharField(
        verbose_name=_("Link"), editable=False, max_length=512,
    )
    poll_url = models.CharField(
        verbose_name=_("Poll url"), editable=False, max_length=512,
    )
    amount = models.DecimalField(max_digits=19, decimal_places=2, null=True, blank=True)


    class Meta:
        verbose_name = _("Paynow transaction")
        verbose_name_plural = _("Paynow transactions")
        ordering = ("-created",)

    @property
    def amount_paid(self):
        # Get paid amount from paynow POLL_URL
        status = self.do_poll()
        if status:
            if status.paid:
                return status.amount
            return 0
        return 0

    @property
    def status(self):
        stat_obj = self.do_poll()
        if stat_obj:
            return stat_obj.status
        return "Error"

    def do_poll(self):
        # Get poll url
        poll_url = self.poll_url
        if poll_url:
            response = requests.post(poll_url, {})
            if response.status_code == 200:
                # Get query string from response
                response_qs = parse_qs(response.text)
                # create_holding_dict
                res = dict()
                # loop query string
                for key, value in response_qs.items():
                    res.update({key: str(value[0])})
                status = StatusResponse(res, False)  # Get StatusResponse object from Paynow
                if status.paid:
                    self.amount = status.amount
                    self.save()
                return status
        return None

    @property
    def paid(self):
        status = self.do_poll()
        if status:
            if status.paid:
                return True
        return False

    def update_debit_ref(self):
        if CreditLedger.objects.filter(transaction=self).exists():
            return
        else:
            if self.paid:
                CreditLedger.objects.create(
                    registration=self.debit_ref.registration,
                    debit_ref=self.debit_ref,
                    narration=self.debit_ref.narration,
                    amount=self.amount_paid,
                    transaction=self,
                    payment_ref="Paynow"
                )
            return

isppme/chat/models.py
from django.db import models

# Create your models here.

isppme/core/models.py
import uuid

from django.db import models

from model_utils.models import TimeStampedModel

class UUIDModel(TimeStampedModel):

    uuid_id = models.UUIDField(
        editable=False, unique=True, default=uuid.uuid4,
    )

    class Meta:
        abstract = True

isppme/members/models.py
from django.db import models

# Create your models here.

isppme/students/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.validators import ValidationError

from isppme.core.models import UUIDModel
from isppme.core.countries import COUNTRIES
from isppme.users.models import get_sentinel_user

from .managers import StudentManager, gen_isppme_reg_number


class Student(UUIDModel):
    """Student record representation.
    Stores all information related to
    a student.
    """
    SEX_CHOICES = (
        ("M", _("Male")),
        ("F", _("Female")),
    )
    reg_number = models.CharField(
        verbose_name=_("Registration number"), max_length=30, default=gen_isppme_reg_number,
        help_text=_("Student registration number. Auto-generated"), editable=False,
    )

    name = models.CharField(
        verbose_name=_("Student name"), max_length=255,
        help_text=_("Full student name"),
    )

    dob = models.DateField(
        verbose_name=_("Date of birth"),
        help_text=_("Student's date of birth.")
    )

    sex = models.CharField(
        verbose_name=_("Sex"), max_length=1, choices=SEX_CHOICES,
        help_text=_("Student's sex orientation")
    )
    place_of_birth = models.CharField(
        verbose_name=_("Place of birth"), max_length=255,
        help_text=_("Student's place of birth")
    )
    national_id = models.CharField(
        verbose_name=_("National ID"), null=True, blank=True, max_length=20,
        help_text=_("Student's national id number as issued by country of nationality")
    )
    passport_number = models.CharField(
        verbose_name=_("Passport number"), null=True, blank=True, max_length=25,
        help_text=_("Student's passport number is applicable")
    )
    nationality = models.CharField(
        choices=COUNTRIES, null=True, blank=True, max_length=255,
        verbose_name=_("Nationality"),
        help_text=_("Student's nationality")
    )
    country_of_permanent_residence = models.CharField(
        choices=COUNTRIES, max_length=255, null=True, blank=True,
        help_text=_("Student's country of permanent residence")
    )
    disabilities = models.TextField(
        verbose_name=_("Disabilities"), max_length=599, blank=True, null=True,
        help_text=_("Disabilities if any")
    )
    contact_address = models.CharField(
        verbose_name=_("Contact Address"), max_length=255,
        help_text=_("Note: All correspondences will be forwarded to this address")
    )
    telephone_number = models.CharField(
        verbose_name=_("Telephone number"), max_length=20, null=True, blank=True,
        help_text=_("Student's home telephone number")
    )
    mobile_number = models.CharField(
        verbose_name=_("Mobile number"), max_length=20, null=True, blank=True,
        help_text=_("Student's mobile phone number")
    )
    email_address = models.EmailField(
        verbose_name=_("Email address"), max_length=255,
        help_text=_("Student's email address")
    )
    is_member = models.BooleanField(
        verbose_name=_("Is student a Member of ISPPME?"), default=False,
        help_text=_("Indicate if student is a member of ISPPME")
    )
    member_id = models.CharField(
        verbose_name=_("Member ID"), max_length=255, null=True, blank=True,
    )
    application_ref = models.OneToOneField(
        to='applications.Application', on_delete=models.SET_NULL, related_name="student", null=True, blank=True,
    )
    user = models.OneToOneField(
        to="users.User", on_delete=models.SET_NULL,
        verbose_name=_("User"), null=True, blank=True,
    )

    objects = StudentManager()

    def set_user(self, user_acc):
        self.user = user_acc
        self.save()

    class Meta:
        verbose_name = _("Student")
        verbose_name_plural = _("Students")

    def __str__(self):
        return f"{str(self.name)}"

    def clean(self):
        if self.dob:
            if self.dob > timezone.now().date():
                raise ValidationError({"dob": _("Date of birth cannot be greater than today.")})

    def save(self, *args, **kwargs):
        new_record = False
        if not self.pk:
            new_record = True
        self.full_clean()
        super(Student, self).save(*args, **kwargs)

    @property
    def full_name(self):
        return f"{self.name}"

    @property
    def initials(self):
        return self.name[:1]

    @property
    def balance(self):
        bal = 0
        for enr in self.enrollments.all():
            bal += enr.balance
        return bal

    @property
    def age(self):
        today = timezone.now().date()
        age = today.year - self.dob.year - (
            (today.month, today.day) < (self.dob.month, self.dob.day))
        return age

    def get_debit_ledger_entries(self):
        from isppme.accounts.models import DebitLedger

        return DebitLedger.objects.filter(
            registration__enrollment__student=self
        )

    def get_credit_ledger_entries(self):
        from isppme.accounts.models import CreditLedger

        return CreditLedger.objects.filter(
            registration__enrollment__student=self
        )

    def courses(self):
        cc = list()
        for enr in self.enrollments.all():
            cc.append(enr.course.__str__())
        return ", ".join(cc)

isppme/staff/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
#
from isppme.semesters.models import Semester
from isppme.exams.models import Exam


class StaffAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                _("This account is inactive."),
                code='inactive',
            )
        if not user.is_staff:
            raise forms.ValidationError(
                _("Account not allowed here."), code="not_allowed"
            )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-prepended'


class AcceptanceForm(forms.Form):
    """
    Form to accept an application
    * Requires that a semester/intake
    be specified upon acceptance.
    """

    application = forms.CharField(
        widget=forms.HiddenInput(), required=True,
    )
    semester = forms.ModelChoiceField(
        queryset=Semester.objects.filter(
            applications_start__lte=timezone.now().date(),
            end__gte=timezone.now().date()
        ).order_by("start"), required=False,
        empty_label="No semester/intake eligible."
    )



class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))


class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = [
            "module",
            "semester",
            "write_date",
            "write_time",
            "points",
        ]
        widgets = {
            "module": forms.HiddenInput(),
            "semester": forms.HiddenInput(),
            "write_time": forms.TimeInput(
                attrs={
                    "data-toggle": "flatpickr",
                    "data-flatpickr-enable-time": "true",
                    "data-flatpickr-no-calendar": "true",
                    "data-flatpickr-alt-format": "H:i",
                    "data-flatpickr-date-format": "H:i"
                }
            ),
            "write_date": forms.DateInput(
                attrs={"data-toggle": "flatpickr"}
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))

isppme/templates/applications/acknowledge.html
{% extends 'applications/base.html' %}
{% load static %}
{% load hosts %}
{% load humanize %}
{% block page_title %}
    Application acknowledgement
{% endblock %}
{% block page_content %}
    <div class="container page__container">
        <div class="card card-form">
            <div class="row no-gutters">
                <div class="col-lg-8 card-body">
                    <div class="row">
                        <div class="col-6">
                            <p>
                                <img width="240" src="{% static 'images/byo.webp' %}"
                            </p>
                            <p><strong class="headings-color">Application Acknowledgement</strong></p>
                            <p class="text-muted">
                                The application for <strong>{{ application.course }}</strong> was reviewed and accepted.
                                This page serves to inform the applicant to confirm their interest in pursuing this
                                course by paying clicking the acknowledge button and following the next steps.
                            </p>
                        </div>
                        <div class="col-6">
                            <p><strong class="headings-color lead">Applicant Details</strong></p>
                            <hr>
                            <p class="text-danger">
                                <strong>Warning:</strong> Only proceed with acknowledgement if this
                                application belongs to you.
                            </p>
                            <p class="text-muted">
                            <dl>
                                <dt class="text-muted">Title</dt>
                                <dd class="lead">{{ application.get_title_display }}.</dd>

                                <dt class="text-muted">Full name(s)</dt>
                                <dd class="lead">{{ application.first_name }} {{ application.last_name }}</dd>

                                <dt class="text-muted">Sex, Age</dt>
                                <dd class="lead">
                                    {{ application.get_sex_display }}, {{ application.age }}
                                    ({{ application.date_of_birth }})
                                </dd>

                                <dt class="text-muted">Nationality</dt>
                                <dd class="lead">
                                    {{ application.get_nationality_display }}
                                </dd>

                            </dl>
                            </p>
                        </div>
                    </div>

                </div>
                <div class="col-lg-4 card-form__body card-body">
                    <div class="card-header__title text-muted mb-2">Course</div>
                    <div class="lead">{{ application.course }}</div>
                    <hr>

                    <p>
                        By clicking "Acknowledge", you agree to the Bulawayo Polytechnic Terms of Service and confirm that
                        the information displayed on this page concerns you as the applicant.
                    </p>
                    <form method="post" action="">
                        {% csrf_token %}
                        <input type="hidden" value="1" name="acknowledge">
                        <button href="#" class="btn btn-primary btn-block">
                            Acknowledge
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

isppme/templates/applications/application_complete.html
{% extends 'applications/base.html' %}
{% load static %}
{% load hosts %}
{% load crispy_forms_tags %}
{% block page_title %}
Application Complete
{% endblock %}
{% block page_content %}
    <div class="container page__container">
        <div class="card shadow-none">
            <div class="card-body">
                <center>
                    <i class="fa fa-check-circle fa-5x text-success"></i>
                    <br>
                    <p class="mt-4">
                        Your application has been successfully submitted. You will receive an email (on this address <span class="text-primary">{{ application.email_address }}</span>) once it has been
                        accepted or further information is required.
                    </p>
                    <br>
                </center>
            </div>
        </div>
    </div>
{% endblock page_content %}
{% block js %}
    {{ block.super }}

{% endblock js %}

isppme/templates/applications/base.html
{% load static %}
{% load hosts %}
{% load core_template_tags_and_filters %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block page_title %}{% endblock %}&bull; </title>

    <!-- Prevent the demo from appearing in search engines -->
    <meta name="robots" content="noindex">

    <link type="text/css" href="{% static 'css/isppme-colors.css' %}" rel="stylesheet">

    <!-- Simplebar -->
    <link type="text/css" href="{% static 'slack-assets/vendor/simplebar.min.css' %}" rel="stylesheet">

    <!-- App CSS -->
    <link type="text/css" href="{% static 'slack-assets/css/app.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'slack-assets/css/app.rtl.css' %}" rel="stylesheet">

    <!-- Material Design Icons -->
    <link type="text/css" href="{% static 'slack-assets/css/vendor-material-icons.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'slack-assets/css/vendor-material-icons.rtl.css' %}" rel="stylesheet">

    <!-- Font Awesome FREE Icons -->
    <link type="text/css" href="{% static 'slack-assets/css/vendor-fontawesome-free.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'slack-assets/css/vendor-fontawesome-free.rtl.css' %}" rel="stylesheet">


    <!-- Flatpickr -->
    <link type="text/css" href="{% static 'slack-assets/css/vendor-flatpickr.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'slack-assets/css/vendor-flatpickr.rtl.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'slack-assets/css/vendor-flatpickr-airbnb.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'slack-assets/css/vendor-flatpickr-airbnb.rtl.css' %}" rel="stylesheet">


</head>

<body class="layout-fixed">

<div class="preloader"></div>

<!-- Header Layout -->
<div class="mdk-header-layout js-mdk-header-layout">

    <!-- Header -->

    <div id="header" class="mdk-header bg-dark js-mdk-header m-0" data-fixed data-effects="waterfall">
        <div class="mdk-header__content">

            <div class="navbar navbar-expand-sm navbar-main navbar-light bg-light  pr-0" id="navbar" data-primary>
                <div class="container-fluid">

                    <!-- Navbar toggler -->

                 


                    <!-- Navbar Brand -->
                    <a href="{% host_url 'index' host 'applications' %}" class="navbar-brand ">
                        <img style="    width: 60px;" src="{% static 'images/byo.webp' %}" class="mr-3" width="110" alt="">
                        <span class="text-isppme"></span>
                    </a>

                    <form class="search-form d-none d-sm-flex flex"
                          action="/">
                        <button class="btn" type="submit" role="button"><i class="material-icons">search</i></button>
                        {% if filter.form.name.value %}
                            <input value="{{ filter.form.name.value }}" type="text" name="name" id="id_name"
                                   class="form-control" placeholder="Search">
                        {% else %}
                            <input type="text" name="name" id="id_name" class="form-control"
                                   placeholder="Search">
                        {% endif %}
                    </form>

                    <ul class="nav navbar-nav ml-auto d-none d-md-flex">
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="material-icons">help_outline</i> Get Help
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
    </div>

    <!-- // END Header -->

    <!-- Header Layout Content -->
    <div class="mdk-header-layout__content page">
        <div class="page__header mb-0">
            <div class="container-fluid page__container">
                <div class="navbar navbar-secondary navbar-light navbar-expand-sm p-0">
                    <button class="navbar-toggler navbar-toggler-right" data-toggle="collapse"
                            data-target="#navbarsExample03" type="button">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse" id="navbarsExample03">
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fa fa-home"></i>  Home
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="javascript:void(0)" class="nav-link dropdown-toggle" data-toggle="dropdown">Login</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% host_url 'login' host 'students' %}">Student
                                        Portal</a>
                                    <a class="dropdown-item" href="{% host_url 'login' host 'teachers' %}">Tutor
                                        Portal</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


        <div class="container  page__heading-container mb-0">
            <div class="page__heading mb-0 mt-0">
                <h4 class="m-0"><i class="fa fa-archive text-muted"></i> <span class="text-isppme text-muted">Course Application</span>
                </h4>
            </div>
        </div>



        {% block page_content %}

        {% endblock page_content %}

    </div>
    <!-- // END Header Layout Content -->

</div>
<!-- // END Header Layout -->

{% block js %}
    <!-- jQuery -->
    <script src="{% static 'slack-assets/vendor/jquery.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'slack-assets/vendor/popper.min.js' %}"></script>
    <script src="{% static 'slack-assets/vendor/bootstrap.min.js' %}"></script>

    <!-- Simplebar -->
    <script src="{% static 'slack-assets/vendor/simplebar.min.js' %}"></script>

    <!-- DOM Factory -->
    <script src="{% static 'slack-assets/vendor/dom-factory.js' %}"></script>

    <!-- MDK -->
    <script src="{% static 'slack-assets/vendor/material-design-kit.js' %}"></script>

    <!-- App -->
    <script src="{% static 'slack-assets/js/toggle-check-all.js' %}"></script>
    <script src="{% static 'slack-assets/js/check-selected-row.js' %}"></script>
    <script src="{% static 'slack-assets/js/dropdown.js' %}"></script>
    <script src="{% static 'slack-assets/js/sidebar-mini.js' %}"></script>
    <script src="{% static 'slack-assets/js/app.js' %}"></script>


    <!-- Flatpickr -->
    <script src="{% static 'slack-assets/vendor/flatpickr/flatpickr.min.js' %}"></script>
    <script src="{% static 'slack-assets/js/flatpickr.js' %}"></script>

{% endblock %}
</body>

</html>

isppme/templates/applications/create_student_account.html
{% extends 'applications/base.html' %}
{% load static %}
{% load hosts %}
{% block page_title %}
Create Student Account
{% endblock %}
{% load crispy_forms_tags %}
{% block page_content %}

    <div class="container page__container">
        <div class="card shadow-none card-form">
            <div class="row no-gutters">
                <div class="col-lg-4 card-body">
                    <p><strong class="headings-color">Account Creation</strong></p>
                    <p class="text-muted">
                        You are almost done now, <strong>{{ application.first_name }}</strong>. Finish registration by
                        creating your account here.
                    </p>
                </div>
                <div class="col-lg-8 card-form__body card-body">
                    <div class="alert alert-primary">
                        Your registration number is <strong>{{ application.student.reg_number }}</strong>. Use this
                        as your username or change it here. You can also change your email address and use the preferred
                        one. Any communication to you will be through this account or email address.
                    </div>
                    {% crispy form %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}